# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  weight = 1
  identifier = "home"

[[main]]
  name = "About"
  url = "#about"
  weight = 1
  parent = "home"

[[main]]
  name = "Featured"
  url = "#featured"
  weight = 2
  parent = "home"

[[main]]
  name = "Twitter"
  url = "#twitter"
  weight = 2
  parent = "home"

[[main]]
  name = "Team"
  url = "#people"
  weight = 3
  parent = "home"

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 4
  parent = "home"

[[main]]
  name = "NeuroBlog"
  weight = 71
  identifier = "blogmenu"

[[main]]
  name = "Start Here"
  url = "blogmenu/"
  weight = 71
  parent = "blogmenu"

[[main]]
  name = "Theme 1"
  url = "theme_1_page/"
  weight = 72
  parent = "blogmenu"

[[main]]
  name = "Theme 2"
  url = "theme_2_page/"
  weight = 73
  parent = "blogmenu"

[[main]]
  name = "Theme 3"
  url = "theme_3_page/"
  weight = 73
  parent = "blogmenu"

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
